# Generated by Django 2.2.4 on 2019-11-20 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0003_keyword_groups_user_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='profit_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('product_name', models.TextField()),
                ('korean_selling_price', models.FloatField(default=0)),
                ('china_price_min', models.FloatField(default=0)),
                ('china_price_max', models.FloatField(default=0)),
                ('china_price_avg', models.FloatField(default=0)),
                ('exchange_rate', models.FloatField(default=0)),
                ('oversea_shipping', models.FloatField(default=0)),
                ('tax_rate', models.FloatField(default=0)),
                ('vat', models.FloatField(default=0)),
                ('local_delievery_cost', models.FloatField(default=0)),
                ('extra_cost', models.FloatField(default=0)),
                ('total_cost_per_piece', models.FloatField(default=0)),
                ('net_profit_min', models.FloatField(default=0)),
                ('net_profit_max', models.FloatField(default=0)),
                ('net_profit_avg', models.FloatField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.profit_groups')),
            ],
        ),
    ]
