# Generated by Django 2.2.4 on 2019-11-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_profit_groups_user_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profit',
            name='korean_selling_price',
        ),
        migrations.RemoveField(
            model_name='user_profit',
            name='net_profit_avg',
        ),
        migrations.RemoveField(
            model_name='user_profit',
            name='net_profit_max',
        ),
        migrations.RemoveField(
            model_name='user_profit',
            name='net_profit_min',
        ),
        migrations.RemoveField(
            model_name='user_profit',
            name='total_cost_per_piece',
        ),
        migrations.AddField(
            model_name='user_profit',
            name='selling_price_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user_profit',
            name='selling_price_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user_profit',
            name='selling_price_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user_profit',
            name='exchange_rate',
            field=models.FloatField(default=1),
        ),
    ]
