# Generated by Django 2.2.7 on 2019-11-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20191121_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profit',
            name='exchange_rate',
            field=models.FloatField(default=167.43),
        ),
    ]
