# Generated by Django 2.2.6 on 2019-11-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20191122_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicture',
            name='my_store_url',
            field=models.URLField(default='http://127.0.0.1:8000/register/'),
            preserve_default=False,
        ),
    ]
