# Generated by Django 2.2.4 on 2019-11-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_user_content_downloader_company_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_content_downloader',
            name='price',
            field=models.FloatField(),
        ),
    ]
