# Generated by Django 2.2.4 on 2019-11-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_user_content_downloader_price_krw'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_supplier_finder',
            name='company_href',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_supplier_finder',
            name='price_krw',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_supplier_finder',
            name='price',
            field=models.FloatField(),
        ),
    ]
