# Generated by Django 2.2.4 on 2019-12-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20191127_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_supplier_finder',
            name='company_href',
        ),
    ]
