# Generated by Django 2.2.4 on 2019-12-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_remove_user_content_downloader_company_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profit',
            name='china_price_avg',
        ),
        migrations.RemoveField(
            model_name='user_profit',
            name='china_price_max',
        ),
        migrations.RemoveField(
            model_name='user_profit',
            name='china_price_min',
        ),
        migrations.RemoveField(
            model_name='user_profit',
            name='key',
        ),
        migrations.RemoveField(
            model_name='user_profit',
            name='selling_price_avg',
        ),
        migrations.RemoveField(
            model_name='user_profit',
            name='selling_price_max',
        ),
        migrations.RemoveField(
            model_name='user_profit',
            name='selling_price_min',
        ),
        migrations.AddField(
            model_name='user_profit',
            name='buying_price_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user_profit',
            name='buying_price_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user_profit',
            name='buying_price_min',
            field=models.FloatField(default=0),
        ),
    ]
