# Generated by Django 2.2.4 on 2019-12-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20191206_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profit',
            name='roi',
            field=models.FloatField(default=100),
        ),
    ]
