# Generated by Django 2.2.4 on 2019-12-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_user_profit_roi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profit',
            name='commision',
            field=models.FloatField(default=0),
        ),
    ]
