# Generated by Django 2.2.4 on 2019-12-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_user_profit_commision'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profit',
            name='sales_goal',
            field=models.IntegerField(default=1),
        ),
    ]
